### PR TITLE
getGlobalContext and default values fixes

### PR DESCRIPTION
**Pull request by skfd**
Hi! Great library, I just want to fix couple of things...

* getGlobalContext -- it was already implemented we needed just to expose it.
* userId is default GUID -- changed int value to valid GUID so code that might parse it works correctly.
* initialise default user variables -- user context should be present event after `initialise` withouth arguments.
* securityRoles, securityRolePrivileges -- empty lists even by default.

Tested this changes against our work project. What do you think?

### CODE REVIEW

**Comment by camelCaseDave** [comment]
Looks good, thanks for the contribution @skfd !

**Comment by skfd** [comment]
oh wow, thank you for excepting the PR. Not sure what broke the build though, sorry

**Comment by camelCaseDave** [comment]
@skfd just some linting errors. I'll fix them now.

**Comment by camelCaseDave** [comment]
All green https://travis-ci.org/camelCaseDave/xrm-mock :+1:

**Comment by skfd** [comment]
Will you be so kind to release new version with these changes? ^_^

**Comment by camelCaseDave** [comment]
> Will you be so kind to release new version with these changes? ^_^

Sure thing. I've just published v3.4.16 https://www.npmjs.com/package/xrm-mock

**Pull request merged**
